# Project information
site_name: LeanIX Report Gallery
site_url: https://stephen-gates.github.io/report-gallery/site
site_author: Stephen Gates
site_description: >-
  Discover the questions you can answer using LeanIX reports.
  
# GitHub Repository displays github details in header 
#repo_url: https://github.com/Stephen-Gates/report-gallery
#repo_name: "Report Gallery"
#edit_uri: edit/master/docs/
#edit_uri: blob/master/docs/

# Copyright
copyright: Copyright &copy; 2020 LeanIX Report Gallery - CC BY-SA 4.0
    
# Configuration
theme:
  name: material
  # specify two scheme for light and dark mode
  palette:
    #- scheme: leanix
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        #icon: material/toggle-switch
        icon: octicons/sun-16
        name: Switch to light mode
    #- scheme: leanix-dark
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        #icon: material/toggle-switch-off-outline
        icon: octicons/moon-16
        name: Switch to dark mode    
  font:
    text: Raleway
    code: Roboto Mono  
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  language: en-custom
  features:
    - search.highlight
    #- toc.autohide
    #- header.hide
    #- navigation.expand
  #clash with insiders custom_dir?   
  custom_dir: overrides 
# if you use edit_uri then default icon appears! Overridden in source.html
  icon:
    repo: fontawesome/brands/github   
  # 404 page
  #static_templates:
    #- 404.html  
    
# CSS overrides for color 
extra_css:
  - stylesheets/extra.css
  
# Customisation 
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SGatesHQ
      name: SGatesHQ on twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sdgates/ 
      name: Stephen Gates on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/Stephen-Gates/report-gallery
      name: LeanIX Report Gallery on GitHub  
    #- icon: material/lightbulb-on-outline
      #link: https://citadelgroup.com.au/eaaas/
      #name: Request a report   
   
# Extensions  
markdown_extensions:
  - pymdownx.snippets:
      base_path: /includes
      check_paths: true
  - markdown.extensions.admonition
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      #permalink: ⚓︎
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde

          
# Extra javascripts including sortable tables     
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

# Insiders improved search - https://squidfunk.github.io/mkdocs-material-insiders/setup/setting-up-site-search/#built-in-search
# only needed here if other plugins are added

plugins:
  - search
  #- img2fig
  
#Google Analytics
google_analytics:
  - UA-176515086-1
  - auto
    
# Page tree - only 2 levels allowed
nav:
  - Home: index.md
  - Reports: reports.md
  - Questions: questions.md
  - Inventory : inventory/index.md  
  - Factsheet Map: factsheet-map/index.md
  - Landscape: 
    - About Landscape reports: landscape/index.md
    - Application Landscape: landscape/application-landscape-reports.md
    - IT Component Landscape: landscape/it-component-landscape-reports.md
    - Project Landscape: landscape/project-landscape-reports.md
  - Matrix:
    - About Matrix reports: matrix/index.md
    - Application Matrix: matrix/application-matrix-reports.md
    - IT Component Matrix: matrix/it-component-matrix-reports.md
    - Project Matrix: matrix/project-matrix-reports.md  
  - Roadmap:
    - About Roadmap reports: roadmap/index.md
    - Application Roadmap: roadmap/application-roadmap-reports.md
    - IT Component Roadmap: roadmap/it-component-roadmap-reports.md
    - Project Roadmap: roadmap/project-roadmap-reports.md  
  - Circle Map: interface/index.md
  - Data Flow: dataflow/index.md        
  - World Map:
    - About World Map reports: location/index.md
    - Application Sourcing: location/application-sourcing-report.md
    - Application Usage: location/application-usage-report.md
    - IT Component Location: location/it-component-location-report.md 
  - Cost: 
    - About Cost reports: cost/index.md
    - Business Capability Costs: cost/business-capability-cost-report.md
    - Project Costs: cost/project-cost-report.md
    - Provider Costs: cost/provider-cost-report.md                 
  - Portfolio:
    - About Portfolio reports: metrics/index.md
    - Application Portfolio: metrics/application-portfolio-report.md
    - Project Portfolio: metrics/project-portfolio-report.md
    - Provider Portfolio: metrics/provider-portfolio-report.md
    - Lifecycle and Age: metrics/lifecycle-and-age-report.md
  - Difficult questions: difficult-questions.md
  - Engaging Stories:
    - Your Application Portfolio: story/index.md
    - Your Projects: story/projects.md
    - Your Plans: story/plans.md
    #- Your Business Capabilities: story/business-capability.md
  - About:
    - Suggest a change: about/index.md
    - Contributors: about/contributors.md
    - Licence: about/licence.md
    - The Project: about/about.md
