# Project information
site_name: LeanIX Report Gallery
site_url: https://stephen-gates.github.io/report-gallery/site
site_author: Stephen Gates
site_description: >-
  Discover the questions you can answer using LeanIX reports.
  
# GitHub Repository displays github details in header 
#repo_url: https://github.com/Stephen-Gates/report-gallery
#repo_name: Stephen-Gates/report-gallery
# Adds pen to top of content and links to edit_uri. Link appends index.md to the uri. Can't link to right location after published
  #edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 LeanIX Report Gallery - CC BY-SA 4.0
    
# Configuration
theme:
  name: material
  palette:
    scheme: leanix
  font:
    text: Raleway
    code: Roboto Mono  
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  #features:
    #- tabs
  custom_dir: overrides 
# if you use edit_uri then default icon appears!    
  icon:
    repo: fontawesome/brands/github   
  # 404 page
  #static_templates:
    #- 404.html  
    
# CSS overrides for color 
extra_css:
  - stylesheets/extra.css
  
# Customisation - these links open in a new tab so internal links don't work well :-(  
extra:
  social:
    #- icon: fontawesome/brands/creative-commons
      #link: /about/licence 
      #name: Licence for LeanIX Report Gallery
    #- icon: fontawesome/brands/twitter
      #link: https://twitter.com/SGatesHQ
      #name: SGatesHQ on twitter
    #- icon: fontawesome/brands/linkedin
      #link: https://www.linkedin.com/in/sdgates/ 
      #name: Stephen Gates on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/Stephen-Gates/report-gallery
      name: LeanIX Report Gallery on GitHub  
    - icon: material/lightbulb-on-outline
      link: https://citadelgroup.com.au/eaaas/
      name: Request a report   
    #- icon: fontawesome/solid/pen
      #link: /about/index
      #name: Contribute to LeanIX Report Gallery
   
# Extensions  
markdown_extensions:
  - admonition  
  - attr_list
  - meta  
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed
  - toc:
      #permalink: true
      toc_depth: 2
          
# Extra javascripts including sortable tables     
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  
# Google Analytics
# google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto
    
# Page tree - only 2 levels allowed
nav:
  - Home: index.md
  - Questions you can answer: questions.md
  - Types of reports: reports.md
  - Factsheet Map: factsheet-map/index.md
  - Metrics:
    - Metrics reports: metrics/index.md
    - Application Portfolio: metrics/application-portfolio-report.md
    - Project Portfolio: metrics/project-portfolio-report.md
    - Provider Portfolio: metrics/provider-portfolio-report.md
    - Lifecycle and Age: metrics/lifecycle-and-age-report.md
  - Cost: 
    - Cost reports: cost/index.md
    - Business Capability Costs: cost/business-capability-cost-report.md
    - Project Costs: cost/project-cost-report.md
    - Provider Costs: cost/provider-cost-report.md    
  - Landscape: 
    - Landscape reports: landscape/index.md
    - Application Landscape: landscape/application-landscape-reports.md
    - IT Component Landscape: landscape/it-component-landscape-reports.md
    - Project Landscape: landscape/project-landscape-reports.md
  - Location:
    - Location reports: location/index.md
    - Application Sourcing: location/application-sourcing-report.md
    - Application Usage: location/application-usage-report.md
    - IT Component Location: location/it-component-location-report.md
  - Interface:
    - Interface reports: interface/index.md
    - Interface Circle Map: interface/interface-circle-map-report.md
    - Data Flow diagram: interface/data-flow-diagram.md        
  - Matrix:
    - Matrix reports: matrix/index.md
    - Application Matrix: matrix/application-matrix-reports.md
    - IT Component Matrix: matrix/it-component-matrix-reports.md
    - Project Matrix: matrix/project-matrix-reports.md
  - Roadmap:
    - Roadmap reports: roadmap/index.md
    - Application Roadmap: roadmap/application-roadmap-reports.md
    - IT Component Roadmap: roadmap/it-component-roadmap-reports.md
    - Project Roadmap: roadmap/project-roadmap-reports.md
  - Inventory : inventory/index.md  
  - Difficult questions: cant-answer.md
  - About:
    - Suggest a change: about/index.md
    - Contributors: about/contributors.md
    - Licence: about/licence.md
    - The Project: about/about.md
